version: 2

before:
  hooks:
    - go mod tidy
    - go fmt ./...
    - go test ./...

builds:
  - id: tq
    main: ./cmd/tq
    binary: tq
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }} -X main.date={{ .CommitDate }}
    mod_timestamp: '{{ .CommitTimestamp }}'
    targets:
      - linux_amd64
      - linux_arm64
      - linux_arm
      - linux_riscv64
      - windows_amd64
      - windows_arm64
      - darwin_amd64
      - darwin_arm64

universal_binaries:
  - id: tq
    replace: true
    name_template: tq

archives:
- id: tq
  formats:
    - tar.gz
  ids:
    - tq
  files:
    - none*
  name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

dockers_v2:
  - id: tools
    ids:
      - tq
    dockerfile: Dockerfile
    images:
      - "ghcr.io/mdm-code/tq"
    tags:
      - "latest"
      - "{{ .Tag }}"
      - "v{{ .Major }}"
    platforms:
      - linux/amd64
      - linux/arm64

checksum:
  name_template: 'sha256sums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

release:
  github:
    owner: mdm-code
    name: tq
  draft: true
  prerelease: auto
  mode: replace

changelog:
  use: github-native

announce:
  skip: true
