name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        go-version: [ '1.21' ]
        os: [ windows-latest, macos-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Set up Go
      uses: actions/setup-go@v4.1.0
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Install dependencies
      run: |
        go version
        go install golang.org/x/lint/golint@latest

    - name: Build
      run: make build

    - name: Test
      run: go test -v -coverprofile='coverage.txt' -covermode='atomic' ./...

    - name: Coverage
      uses: codecov/codecov-action@v3.1.4
