name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    strategy:
      matrix:
        go: [ '1.26' ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.go }}/${{ matrix.os }}

    steps:
    - name: Set up Go
      uses: actions/setup-go@v5.4.0
      with:
        go-version: ${{ matrix.go }}

    - name: Checkout
      uses: actions/checkout@v4.2.0
      with:
        fetch-depth: 0

    - name: Run linters with golangci-lint
      uses: golangci/golangci-lint-action@v9
      with:
        version: 2.13.1
